openapi: 3.0.0
info:
  title: API Identidad y Onboarding - NuBank
  version: 1.0.0
  description: API para registro, autenticación, verificación KYC y perfil de usuario.
servers:
  - url: http://localhost:4000
paths:
  /api/v1/auth/register:
    post:
      summary: Registro de nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuario registrado
        '400':
          description: Error de validación
  /api/v1/auth/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login exitoso
        '400':
          description: Credenciales inválidas
  /api/v1/kyc/verify:
    post:
      summary: Verificación de identidad (KYC)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                documents:
                  type: object
      responses:
        '200':
          description: Estado de verificación
        '400':
          description: Error
  /api/v1/users/me:
    get:
      summary: Obtener perfil del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Perfil de usuario
        '401':
          description: No autenticado
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 